# Generated by Django 2.0.5 on 2018-08-08 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('role', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Comments',
                'ordering': ['study', 'output', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=400)),
                ('ex_context', models.CharField(max_length=30)),
                ('ex_code', models.CharField(max_length=30)),
                ('document', models.CharField(max_length=30)),
                ('pages', models.CharField(max_length=30)),
                ('variable', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Description',
            },
        ),
        migrations.CreateModel(
            name='ListCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=30)),
                ('label', models.CharField(max_length=30)),
                ('codelist', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=15)),
                ('order', models.CharField(max_length=4)),
                ('term', models.CharField(max_length=200)),
                ('termcode', models.CharField(max_length=30)),
                ('decode', models.TextField(max_length=400)),
            ],
            options={
                'verbose_name': 'Code List',
            },
        ),
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('title', models.TextField(max_length=400)),
                ('footnote', models.TextField(max_length=400)),
                ('population', models.CharField(max_length=50)),
                ('program', models.CharField(max_length=20)),
                ('programmer', models.CharField(max_length=42)),
                ('indata', models.CharField(max_length=50)),
                ('software', models.CharField(choices=[('SAS', 'SAS'), ('R', 'R'), ('Python', 'Python')], default='SAS', max_length=10)),
                ('qcprogram', models.CharField(max_length=20)),
                ('qcprogrammer', models.CharField(max_length=42)),
                ('qcsoftware', models.CharField(choices=[('SAS', 'SAS'), ('R', 'R'), ('Python', 'Python')], default='SAS', max_length=10)),
                ('statistician', models.CharField(max_length=50)),
                ('outputfile', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('Not started', 'Not Started'), ('Production', 'Production')], default='DRAFT', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figures.Objet')),
            ],
            options={
                'verbose_name': 'Output',
                'ordering': ['study', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Specs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=20)),
                ('variable', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=50)),
                ('data_type', models.CharField(max_length=20)),
                ('length', models.CharField(max_length=5)),
                ('significant_digit', models.CharField(max_length=5)),
                ('format', models.CharField(max_length=42)),
                ('mandatory', models.CharField(max_length=3)),
                ('codelist', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=20)),
                ('pages', models.CharField(max_length=5)),
                ('method', models.CharField(max_length=20)),
                ('predecessor', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=100)),
                ('derivation', models.TextField(max_length=400)),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figures.Objet')),
            ],
            options={
                'verbose_name': 'Data Specifications',
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('title', models.TextField(max_length=400)),
                ('phase', models.CharField(max_length=10)),
                ('Table', models.IntegerField(default=0)),
                ('Listing', models.IntegerField(default=0)),
                ('Figure', models.IntegerField(default=0)),
                ('SDTM', models.IntegerField(default=0)),
                ('ADAM', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('study', models.ManyToManyField(to='figures.Study')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='specs',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figures.Study'),
        ),
        migrations.AddField(
            model_name='output',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figures.Study'),
        ),
        migrations.AddField(
            model_name='listcode',
            name='objet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figures.Objet'),
        ),
        migrations.AddField(
            model_name='listcode',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figures.Study'),
        ),
        migrations.AddField(
            model_name='description',
            name='objet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figures.Objet'),
        ),
        migrations.AddField(
            model_name='description',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figures.Study'),
        ),
        migrations.AddField(
            model_name='comment',
            name='objet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figures.Objet'),
        ),
        migrations.AddField(
            model_name='comment',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figures.Output'),
        ),
        migrations.AddField(
            model_name='comment',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figures.Study'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
