# Generated by Django 2.0.5 on 2018-08-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extension',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='nom',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
