# Generated by Django 2.0.5 on 2018-08-13 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0003_auto_20180813_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='document',
            name='nom',
        ),
    ]
