# Generated by Django 2.0.5 on 2018-08-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0007_auto_20180817_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='domain',
            field=models.CharField(choices=[('ADAE', 'ADAE'), ('ADSL', 'ADSL'), ('ADVS', 'ADVS'), ('ADLB', 'ADLB'), ('ADEG', 'ADEG'), ('ADPC', 'ADPC'), ('ADPP', 'ADPP')], default='ADSL', max_length=20),
        ),
    ]
