# Generated by Django 2.0.5 on 2018-09-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0009_dataset_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('SDTM', 'SDTM'), ('ADAM', 'ADAM'), ('RAW', 'RAW')], default='ADAM', max_length=5),
        ),
        migrations.AlterField(
            model_name='document',
            name='domain',
            field=models.CharField(choices=[('ADAE', 'ADAE'), ('ADSL', 'ADSL'), ('ADVS', 'ADVS'), ('ADLB', 'ADLB'), ('ADEG', 'ADEG'), ('ADPC', 'ADPC'), ('ADPP', 'ADPP'), ('DM', 'DM'), ('EG', 'EG'), ('VS', 'VS'), ('AE', 'AE'), ('SV', 'SV'), ('LB', 'LB'), ('TA', 'TA')], default='ADSL', max_length=20),
        ),
    ]
