# Generated by Django 2.0.5 on 2018-10-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0010_auto_20180925_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pop_flag',
            field=models.TextField(default='SAFFL', max_length=400),
            preserve_default=False,
        ),
    ]
