# Generated by Django 2.0.5 on 2018-10-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0011_document_pop_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='variables',
            field=models.TextField(default='USUBJID', max_length=1000),
            preserve_default=False,
        ),
    ]
