# Generated by Django 2.1.5 on 2019-03-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0013_document_study_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='arms',
            field=models.TextField(default='De', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='n_pop_flag',
            field=models.CharField(default='De', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='number_of_subj',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
